config/routes.rb
Rails.application.routes.draw do
  resources :blogs do 
  	resources :comments
  end
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
  validates :name, presence: true
  before_validation :en_v

  private

  def en_v
  	puts "inside en v"
  		self.name = "sunil"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  # around_action :abc
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.joins(:user, :comments)
                  .order('blogs.id DESC')
                  .select('blogs.*', 'users.email as uemail', 'comments.body as cbody')
  end



  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:name, :user_id)
    end

  def abc
    puts "helloooooooooooooooooooooooooooooooooooooooo"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :load_commentable
	def index
	    @comments = @commentable.comments
	end

	def new
	    @comment = @commentable.comments.new
	end

	def create
		@comment = @commentable.comments.new comments_params
		# @comment.user = current_user
		@comment.save!
		redirect_to @commentable, notice: "Your comment was successfully posted."
	end

    def update
		@comment = Comment.find(params[:id])
	    if @comment.update_attributes(comment_params)
	      redirect_to @comment.commentable, notice: "Comment was updated."
	    else
	      render :edit
	    end
    end

   def destroy
    @comment.destroy
    redirect_to @comment.commentable, notice: "Comment destroyed."
   end

	private

	def load_commentable
	    resource, id = request.path.split('/')[1, 2]
	    @commentable = resource.singularize.classify.constantize.find(id)
	end

	def comments_params
		params.require(:comment).permit(:body)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>
<%= link_to 'New Blog', new_blog_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.name %></td>
        <td><%= blog.uemail %></td>
        <td>
          <%= blog.cbody%>
        </td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blog.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @blog.user.email %>
</p>
<%= render partial: "comments/comments", locals: {commentable: @blog}%>
<%= render partial: "comments/form", locals: {commentable: @blog}%>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/comments/_comments.html.erb
<div>
	<h1>Comment</h1>
	<% commentable.comments.each do |c|%>
	<div style="padding-right: 20px;"><%= c.body%><span>
		<%= link_to 'Edit', edit_blog_comment_path(c.id) %>
	</span></div>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for [commentable, Comment.new] do |form| %>
  <% if commentable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(commentable.errors.count, "error") %> prohibited this commentable from being saved:</h2>

      <ul>
      <% commentable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div>

    <%= yield %>
  </body>
</html>